<?php

namespace Alex\PlatformBundle\Repository;

/**
 * Seance_Exercice_SerieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Seance_Exercice_SerieRepository extends \Doctrine\ORM\EntityRepository
{
}
